### ISSUE TITLE
Not clear on implementation

### ISSUE THREAD

**Issue by moskalyk** [aecepoglu/concourse-bitbucket-pullrequest-resource#1]
I know you just released this, but I want to give immediate feedback as I followed the steps in the example and was not able to get the proper results. I even added a `trigger: true` step because I assumed you need that in order for this to be automatic.

Here were my steps:
1. Set pipeline in concourse 
2. Push code to Bitbucket
3. Create PR

Here is my pipeline (note that the values are being injected before running pipeline)

````

resource_types:
- name: bitbucket-pr
  type: docker-image
  source:
    repository: aeecepoglu/concourse-bitbucket-pr-resource

resources:
- name: new-pr
  type: bitbucket-pr
  source:
    username: (( grab meta.bitbucket.username ))
    password: (( grab meta.bitbucket.password ))
    url: (( grab meta.bitbucket.url ))
    project: (( grab meta.bitbucket.project ))
    repo: (( grab meta.bitbucket.repo ))
    private_key: (( grab meta.git.private-key ))

jobs: 
- name: tree
  plan:
    - get: new-pr
      trigger: true
    - task: tree
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        inputs:
          - name: new-pr
        run:
          path: tree

**Comment by aecepoglu** [comment]
Are you receiving any errors while checking for resource or retrieving checked resources?

What does `fly -t CONCOURSE_TARGET cp -p YOUR_PIPELINE/new-pr` give?

**Comment by moskalyk** [comment]
➜  ci git:(feature/0/test) ✗ 👉  fly -t lite cp -p artifactory-rest-test/new-pr
error: Unknown command `cp', did you mean `abort-build'?

What does cp supposed to do? I didn't find it in the help section.

**Comment by moskalyk** [comment]
I'd like to help contribute on this resource, is there a way to PM you via email / slack and walk me through how I'd go about debugging the plugin?

I tried the second instruction, to send the GET request. And I got back a valid 200 OK response:

````
{
  "size": 1,
  "limit": 25,
  "isLastPage": true,
  "values": [
    {
      "id": 3,
      "version": 0,
      "title": "Feature/0/local test",
      "description": "* .\r\n* adding",
      "state": "OPEN",
      "open": true,
      "closed": false,
      "createdDate": 1479259626507,
      "updatedDate": 1479259626507,

...
}

**Comment by aecepoglu** [comment]
Oh that was a typo, I meant `cr` as in "check resource"

**Comment by moskalyk** [comment]
Yeah that worked! I was able to show the error:

````
error: check failed with exit status '1':
failed to fetch digest: 401 Unauthorized
```

Which is strange because I'm using the same credentials as if I were to make a request with Postman. How does one debug the python code before packaging as a docker image for concourse to consume? 

My bitbucket is running as a Bitbucket server on my local computer in a docker container. That has nothing to do with it right?

**Comment by aecepoglu** [comment]
I think we solved this on slack

**Comment by dolph** [comment]
WHO WERE YOU, DENVERCODER9? _WHAT DID YOU SEE?_

**Comment by aecepoglu** [comment]
@dolph Oh I'm sorry about that. But this should have been a separate issue, from the looks of it.

I'm glad you figured it out. Enjoy-
