### ISSUE TITLE
URL Needs to be an IP

### ISSUE THREAD

**Issue by moskalyk** [aecepoglu/concourse-bitbucket-pullrequest-resource#2]
I found that in order for this resource to work, an IP address is required. When I try using a domain name that is a CNAME for my IP, it doesn't work. (e.g. something ends in a .com)

```
Cloning into '/tmp/repo'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Also, even though I'm using port 80, I have to explicitly state that for the PR to pick up my bitbucket resource when trying to use the feature of clone repo as well.

Maybe just update the README.md to reflect this.

**Comment by aecepoglu** [comment]
Okay I can make the default value for the port to be 80. That's easy.

About domain name not resolving, it may be true. I'll have to try and see and update the README as necessary.

**Comment by aecepoglu** [comment]
I've decided I shouldn't do the default-port change. I'll update the documentation as so:

    You may need to define the port number explicitly in the URL, even if it is 80.

I haven't been able to reproduce the domain name resolution issue. Is it an internal domain or an external one?

**Comment by aecepoglu** [comment]
I have tried what you suggested and domain names seem to be resolving fine.

If you're using internal domains, it's normal for a concourse resource not to be able to resolve an internal domain name. **`resolve_hostnames` option can help you resolve any internal hostname**. 

1. What values are you using?
2. Where is the bitbucket host that you are unable to access? Internal or external?
3. Can you ping that host from your computer?
4. Does the `resolve_hostnames` option help?

Please reopen if your issue continues
